version: '3.8'

services:
  api-backend:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    container_name: api-backend
    image: node:14-alpine
    volumes:
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - ../../.env
    depends_on:
      - api-static
  api-static:
    container_name: api-static
    image: minio/minio
    volumes:
      - ../../${COMPOSE_API_STATIC_VOLUMES_BASE_PATH}:/data
    ports:
      - ${COMPOSE_API_STATIC_PORT}:9000
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ${API_S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${API_S3_ACCESS_SECRET_KEY}
      MINIO_DEFAULT_BUCKETS: default,${API_S3_BUCKET}
    networks:
      lan:
        ipv4_address: ${COMPOSE_LAN_API_STATIC_IP}

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${COMPOSE_LAN_SUBNET}
